import React from "react";
import {
    MDBCard,
    MDBCardHeader,
    MDBCardBody,
    MDBCardTitle,
    MDBCardText,
} from "mdb-react-ui-kit";
import { Button } from "react-bootstrap";

function HomeInfo() {
    return (
        <MDBCard className="text-white">
            <MDBCardBody className="bg-gradient-to-tr from-pink-500 via-blue-800 to-cyan-500">
                <MDBCardHeader class="bg-transparent">
                    <h3> What is Text-To-Speech?</h3>
                </MDBCardHeader>

                <MDBCardText class="bg-transparent-black rounded-lg" >
                    Text to speech (TTS) is a technology that converts written
                    text into spoken words. It enables computers and devices to
                    audibly communicate information to users. Through TTS,
                    written content, such as articles, documents, or web pages,
                    can be transformed into audio format, allowing individuals
                    to listen to the information rather than reading it. This
                    technology has a wide range of applications, including
                    accessibility for individuals with visual impairments,
                    aiding in language learning, facilitating hands-free
                    operation of devices, and providing auditory feedback in
                    various digital interfaces. TTS systems use synthetic voices
                    generated by algorithms to replicate human speech patterns,
                    allowing for natural and intelligible audio output. This
                    technology plays a crucial role in making information more
                    accessible and inclusive for diverse audiences.
                </MDBCardText>
                <Button href="/TtsAiPage">Try it Out</Button>
            </MDBCardBody>
        </MDBCard>
    );
}

export default HomeInfo;
